name: CommediaDellarteWeb
version: 1.0-SNAPSHOT
main: org.red.minecraft.dellarte.web.CommediaDellarteWebPlugin
authors: Double_Z_
api-version: 1.17
description: Dellarte addon display server data in web

depend:
  - CommediaDellarte

web: