name: CommediaDellarte
version: 3.1-SNAPSHOT
main: org.red.minecraft.dellarte.CommediaDellartePlugin
authors: [Double_Z_]
api-version: 1.17
description: Final Dellarte

softdepend:
  - Vault
  - PlaceholderAPI

commands:
  a_economy:
    description: Using for Vault
    aliases: [ae]
    permission: a.economy
    usage: "/<command> <get|set|add> <player> [money]"
  money:
    description: Check or send your balance
    usage: "/<command> [send <player> <money>]"